---
apiVersion: REPLACE_API_VERSION
kind: StatefulSet
metadata:
  labels:
    app: slashing-protector-test
  name: slashing-protector-test
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: slashing-protector-test
  serviceName: slashing-protector-test
  template:
    metadata:
      labels:
        app: slashing-protector-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - ethereum2_validators      
      containers:
      - name: slashing-protector-test
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        command: ["/app/slashing-protector"]
        env:
        - name: DB_PATH
          value: /data
        - name: ADDR
          value: ":9369"
        ports:
        - containerPort: 9369
          name: port-9369
        volumeMounts:
        - mountPath: "/data/"
          name: nfs-volume
      volumes:
      - persistentVolumeClaim:
          claimName: nfs-validators
        name: nfs-volume
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/role
        operator: Exists 
