---
apiVersion: v1
kind: Service
metadata:
  name: slashing-protector-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: slashing-protector
spec:
  type: ClusterIP
  ports:
    - port: 9369
      protocol: TCP
      targetPort: 9369
      name: port-9369
  selector:
    app: slashing-protector
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: slashing-protector
  name: slashing-protector
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slashing-protector
  template:
    metadata:
      labels:
        app: slashing-protector
    spec:
      containers:
      - name: slashing-protector
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        command: ["/app/slashing-protector"]
        env:
        - name: DB_PATH
          value: /app/tmp
        - name: ADDR
          value: ":9369"
        ports:
        - containerPort: 9369
          name: port-9369
