version: '3'

services:
  server:
    build:
      context: .
    ports:
      - 9369:9369
    volumes:
      - ./tmp:/data
    environment:
      - DB_PATH=${DB_PATH:-/data}
      - ADDR=${ADDR:-:9369}
    restart: always
