version: '3'

services:
  server-1:
    build:
      context: .
    ports:
      - 9469:9369
    volumes:
      - ./.tmp:/data
    environment:
      - DB_PATH=${DB_PATH:-/data}
      - ADDR=${ADDR:-:9369}
  server-2:
    build:
      context: .
    ports:
      - 9470:9369
    volumes:
      - ./.tmp:/data
    environment:
      - DB_PATH=${DB_PATH:-/data}
      - ADDR=${ADDR:-:9369}
  server-3:
    build:
      context: .
    ports:
      - 9471:9369
    volumes:
      - ./.tmp:/data
    environment:
      - DB_PATH=${DB_PATH:-/data}
      - ADDR=${ADDR:-:9369}
