version: '3'

services:
  server:
    build:
      context: .
    ports:
      - 9369:9369
    volumes:
      - ./tmp:/app/tmp
    environment:
      - DB_PATH=${DB_PATH:-/app/tmp}
      - ADDR=${ADDR:-9369}
    restart: always
