# Default values for contract-center-worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3
namespace: validators

image:
  repository: 764289642555.dkr.ecr.us-west-2.amazonaws.com/slashing-protector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service:
  type: ClusterIP
  port: 9369

resources:
  limits:
    cpu: 500m
    memory: 1024Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/role
              operator: In
              values:
                - ethereum2_validators
tolerations:
  - effect: NoSchedule
    key: kubernetes.io/role
    operator: Exists
